artifacts:
  data:
    path: data
    type: dataset
    desc: Datasets
  model_msk:
    path: models/msk
    desc: Housing prices prediction for msk
    type: model
    labels:
    - msk
    - AutoGluon
  model_ru:
    path: models/ru
    desc: Housing prices prediction for whole Russia
    type: model
    labels:
    - ru
    - AutoGluon

stages:
  prepare_msk:
    cmd: python src/prepare_msk.py ${prepare_msk.test_size} ${prepare_msk.validation_size}
    deps:
    - data/additional_data
    - data/avito_data
    - src/prepare_msk.py
    params:
    - prepare_msk.test_size
    - prepare_msk.validation_size
    outs:
    - data/prepared/msk

  prepare_ru:
    cmd: python src/prepare_ru.py ${prepare_ru.test_size} ${prepare_ru.validation_size}
    deps:
    - data/additional_data
    - data/avito_data
    - src/prepare_ru.py
    params:
    - prepare_ru.test_size
    - prepare_ru.validation_size
    outs:
    - data/prepared/ru

  train_msk:
    cmd: python src/train.py data/prepared/msk/msk_prepared.csv models/msk msk ${train_msk.time_limit} ${train_msk.presets}
    deps:
    - data/prepared/msk/msk_prepared.csv
    - src/train.py
    params:
    - train_msk.time_limit
    - train_msk.presets
    outs:
    - models/msk

  train_ru:
    cmd: python src/train.py data/prepared/ru/ru_prepared.csv models/ru ru ${train_ru.time_limit} ${train_ru.presets}
    deps:
    - data/prepared/ru/ru_prepared.csv
    - src/train.py
    params:
    - train_ru.time_limit
    - train_ru.presets
    outs:
    - models/ru

  evaluate_msk:
    cmd: >
      python src/evaluate.py 
      data/prepared/msk/msk_prepared.csv 
      models/msk 
      msk 
      ${evaluate.metrics} 
      ${evaluate.plot_residuals} 
      ${evaluate.plot_perfect_predictions}
    deps:
    - data/prepared/msk/msk_prepared.csv
    - models/msk
    - src/evaluate.py
    params:
    - evaluate.metrics
    - evaluate.plot_residuals
    - evaluate.plot_perfect_predictions
    outs:
    - metrics/msk_metrics.json:
        cache: false
    - plots/msk:
        cache: false

  evaluate_ru:
    cmd: >
      python src/evaluate.py 
      data/prepared/ru/ru_prepared.csv 
      models/ru 
      ru 
      ${evaluate.metrics} 
      ${evaluate.plot_residuals} 
      ${evaluate.plot_perfect_predictions}
    deps:
    - data/prepared/ru/ru_prepared.csv
    - models/ru
    - src/evaluate.py
    params:
    - evaluate.metrics
    - evaluate.plot_residuals
    - evaluate.plot_perfect_predictions
    outs:
    - metrics/ru_metrics.json:
        cache: false
    - plots/ru:
        cache: false