artifacts:
  data:
    path: data
    type: dataset
    desc: Datasets
  msk:
    path: models/msk
    type: model
    desc: House price prediction for msk model
    labels:
    - AutoGluon
    - msk
  ru:
    path: models/ru
    type: model
    desc: House price prediction for ru model
    labels:
    - AutoGluon
    - ru
stages:
  prepare_msk:
    cmd: python src/prepare_msk.py
    deps:
    - data/additional_data
    - data/avito_data
    - src/prepare_msk.py
    params:
    - prepare_msk
    outs:
    - data/prepared/msk

  prepare_ru:
    cmd: python src/prepare_ru.py
    deps:
    - data/additional_data
    - data/avito_data
    - src/prepare_ru.py
    params:
    - prepare_ru
    outs:
    - data/prepared/ru

  train_models:
    cmd: python src/train.py
    deps:
    - data/prepared/msk/train.csv
    - data/prepared/msk/test.csv
    - data/prepared/ru/train.csv
    - data/prepared/ru/test.csv
    - src/train.py
    params:
    - train_msk
    - train_ru
    outs:
    - models/msk
    - models/ru
    metrics:
    - dvclive_msk/metrics.json:
        cache: false
    - dvclive_ru/metrics.json:
        cache: false
    plots:
    - dvclive_msk/plots:
        cache: false
    - dvclive_ru/plots:
        cache: false

params:
- params.yaml
- dvclive_msk/params.yaml
- dvclive_ru/params.yaml
metrics:
- dvclive_msk/metrics.json
- dvclive_ru/metrics.json
plots:
- dvclive_msk/plots/metrics:
    x: step
- dvclive_ru/plots/metrics:
    x: step
