name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi=0.111.1
  - uvicorn=0.30.1
  - pip
  - cmake
  - pip:
    - --no-binary lightgbm 
    - lightgbm
    - autogluon==1.1.1
    - python-dotenv==1.0.1
    - dvclive==3.47.0
    - python-box==7.2.0
    - dvc[gdrive]==3.51.2
    - mypy
    